language: node_js
dist: xenial
os:
  - linux
  - osx
  - windows
node_js:
  - 'stable'
  - '12'
  - '10'
  - '8'
  - '6'
  - '4'
  - '0.12'
  - '0.10'
  - '0.8'
before_install:
  - 'if [ "${TRAVIS_OS_NAME}" != "windows" ] && [[ "${TRAVIS_NODE_VERSION}" == 0.* ]]; then nvm install-latest-npm; fi'
matrix:
  fast_finish: true
  exclude:
    # hard to get to work
    - os: windows
      node_js: '0.8'
    # it has a different name on windows 🙄
    - os: windows
      node_js: 'stable'
  include:
    - os: windows
      node_js: 'latest'
