language: node_js
dist: xenial
os:
  - linux
  - osx
  - windows
node_js:
  - 'stable'
  - '12'
  - '10'
  - '8'
  - '6'
  - '4'
  - '0.12'
  - '0.10'
  - '0.8'
before_install:
  - 'if [ "${TRAVIS_OS_NAME}" != "windows" ] && [[ "${TRAVIS_NODE_VERSION}" == 0.* ]]; then nvm install-latest-npm; fi'
matrix:
  fast_finish: true
